## Scraping Data from a Real Website

In [18]:
from bs4 import BeautifulSoup
import requests

In [19]:
url = 'https://www.worldometers.info/world-population/population-by-country/'
page = requests.get(url)

page.encoding = "utf-8"

soup = BeautifulSoup(page.text, 'html')

In [ ]:
print(soup)

In [ ]:
soup.find('table')

In [ ]:
# similar output
soup.find_all('table', class_= 'datatable w-full border border-zinc-200' )

In [21]:
table = soup.find('table')

In [22]:
world_titles = soup.find_all('th')

In [23]:
world_titles

[<th class="border-e border-zinc-200 px-2 text-center align-middle border-b-3 py-1 font-semibold" data-sortable="true"> <span>#</span> </th>,
 <th class="border-e border-zinc-200 px-2 text-center align-middle border-b-3 py-1 font-semibold" data-sortable="true"> <span>Country (or dependency)</span> </th>,
 <th class="border-e border-zinc-200 px-2 text-center align-middle border-b-3 py-1 font-semibold" data-sortable="true" data-type="number"> <span>Population 2026</span> </th>,
 <th class="border-e border-zinc-200 px-2 text-center align-middle border-b-3 py-1 font-semibold" data-sortable="true" data-type="number"> <span>Yearly Change</span> </th>,
 <th class="border-e border-zinc-200 px-2 text-center align-middle border-b-3 py-1 font-semibold" data-sortable="true" data-type="number"> <span>Net Change</span> </th>,
 <th class="border-e border-zinc-200 px-2 text-center align-middle border-b-3 py-1 font-semibold" data-sortable="true" data-type="number"> <span>Density (P/Km²)</span> </th>,
 <th class="border-e border-zinc-200 px-2 text-center align-middle border-b-3 py-1 font-semibold" data-sortable="true" data-type="number"> <span>Land Area (Km²)</span> </th>,
 <th class="border-e border-zinc-200 px-2 text-center align-middle border-b-3 py-1 font-semibold" data-sortable="true" data-type="number"> <span>Migrants (net)</span> </th>,
 <th class="border-e border-zinc-200 px-2 text-center align-middle border-b-3 py-1 font-semibold" data-sortable="true" data-type="number"> <span>Fert. Rate</span> </th>,
 <th class="border-e border-zinc-200 px-2 text-center align-middle border-b-3 py-1 font-semibold" data-sortable="true" data-type="number"> <span>Median Age</span> </th>,
 <th class="border-e border-zinc-200 px-2 text-center align-middle border-b-3 py-1 font-semibold" data-sortable="true" data-type="number"> <span>Urban Pop %</span> </th>,
 <th class="border-e border-zinc-200 px-2 text-center align-middle border-b-3 py-1 font-semibold" data-sortable="true" data-type="number"> <span>World Share</span> </th>]

In [24]:
world_table_titles = [title.text for title in world_titles]

print(world_table_titles)

[' # ', ' Country (or dependency) ', ' Population 2026 ', ' Yearly Change ', ' Net Change ', ' Density (P/Km²) ', ' Land Area (Km²) ', ' Migrants (net) ', ' Fert. Rate ', ' Median Age ', ' Urban Pop % ', ' World Share ']

In [25]:
import pandas as pd

df = pd.DataFrame(columns = world_table_titles)

df

Empty DataFrame
Columns: [ # ,  Country (or dependency) ,  Population 2026 ,  Yearly Change ,  Net Change ,  Density (P/Km²) ,  Land Area (Km²) ,  Migrants (net) ,  Fert. Rate ,  Median Age ,  Urban Pop % ,  World Share ]
Index: []

In [26]:
column_data = soup.find_all('tr')

In [27]:
for row in column_data[1:]:
    row_data = row.find_all('td')
    individual_row_data = [data.text for data in row_data]
    print(individual_row_data)

[' 1 ', '  India  ', ' 1,476,625,576 ', ' 0.87% ', ' 12,760,051 ', ' 497 ', ' 2,973,190 ', ' −440,456 ', ' 1.93 ', ' 29.2 ', ' 37.6% ', ' 17.8% ']
[' 2 ', '  China  ', ' 1,412,914,089 ', ' −0.22% ', ' −3,182,005 ', ' 150 ', ' 9,388,211 ', ' −232,107 ', ' 1.03 ', ' 40.6 ', ' 68.7% ', ' 17% ']
[' 3 ', '  United States  ', ' 349,035,494 ', ' 0.51% ', ' 1,759,687 ', ' 38 ', ' 9,147,420 ', ' 1,177,848 ', ' 1.63 ', ' 38.7 ', ' 83.1% ', ' 4.2% ']
[' 4 ', '  Indonesia  ', ' 287,886,782 ', ' 0.76% ', ' 2,165,546 ', ' 159 ', ' 1,811,570 ', ' −39,472 ', ' 2.08 ', ' 30.7 ', ' 60.3% ', ' 3.5% ']
[' 5 ', '  Pakistan  ', ' 259,299,791 ', ' 1.6% ', ' 4,080,237 ', ' 336 ', ' 770,880 ', ' −1,144,738 ', ' 3.44 ', ' 20.8 ', ' 34.7% ', ' 3.1% ']
[' 6 ', '  Nigeria  ', ' 242,431,832 ', ' 2.06% ', ' 4,904,050 ', ' 266 ', ' 910,770 ', ' −2,810 ', ' 4.21 ', ' 18.3 ', ' 55.8% ', ' 2.9% ']
[' 7 ', '  Brazil  ', ' 213,562,666 ', ' 0.35% ', ' 750,261 ', ' 26 ', ' 8,358,140 ', ' −205,642 ', ' 1.59 ', ' 35.3 ', ' 91.7% ', ' 2.6% ']
[' 8 ', '  Bangladesh  ', ' 177,818,044 ', ' 1.21% ', ' 2,131,145 ', ' 1,366 ', ' 130,170 ', ' −371,398 ', ' 2.09 ', ' 26.3 ', ' 43.2% ', ' 2.1% ']
[' 9 ', '  Russia  ', ' 143,394,458 ', ' −0.42% ', ' −602,935 ', ' 9 ', ' 16,376,870 ', ' 324,924 ', ' 1.47 ', ' 40.7 ', ' 75.4% ', ' 1.7% ']
[' 10 ', '  Ethiopia  ', ' 138,902,185 ', ' 2.53% ', ' 3,430,134 ', ' 139 ', ' 1,000,000 ', ' 27,298 ', ' 3.72 ', ' 19.3 ', ' 22.9% ', ' 1.7% ']
[' 11 ', '  Mexico  ', ' 132,997,658 ', ' 0.8% ', ' 1,050,758 ', ' 68 ', ' 1,943,950 ', ' −109,844 ', ' 1.85 ', ' 30 ', ' 88.3% ', ' 1.6% ']
[' 12 ', '  Japan  ', ' 122,427,731 ', ' −0.55% ', ' −675,748 ', ' 336 ', ' 364,555 ', ' 128,619 ', ' 1.23 ', ' 50.2 ', ' 93.4% ', ' 1.5% ']
[' 13 ', '  Egypt  ', ' 120,101,175 ', ' 1.47% ', ' 1,735,180 ', ' 121 ', ' 995,450 ', ' −52,287 ', ' 2.68 ', ' 24.7 ', ' 41.1% ', ' 1.4% ']
[' 14 ', '  Philippines  ', ' 117,724,471 ', ' 0.8% ', ' 937,509 ', ' 395 ', ' 298,170 ', ' −144,275 ', ' 1.86 ', ' 26.6 ', ' 49.9% ', ' 1.4% ']
[' 15 ', '  DR Congo  ', ' 116,452,162 ', ' 3.21% ', ' 3,619,689 ', ' 51 ', ' 2,267,050 ', ' −28,843 ', ' 5.8 ', ' 15.9 ', ' 45.4% ', ' 1.4% ']
[' 16 ', '  Vietnam  ', ' 102,177,431 ', ' 0.57% ', ' 578,904 ', ' 330 ', ' 310,070 ', ' −51,045 ', ' 1.86 ', ' 33.9 ', ' 42.2% ', ' 1.2% ']
[' 17 ', '  Iran  ', ' 93,168,497 ', ' 0.81% ', ' 750,816 ', ' 57 ', ' 1,628,550 ', ' 66,848 ', ' 1.66 ', ' 34.5 ', ' 73.5% ', ' 1.1% ']
[' 18 ', '  Turkey  ', ' 87,926,082 ', ' 0.27% ', ' 240,656 ', ' 114 ', ' 769,630 ', ' −217,896 ', ' 1.62 ', ' 33.9 ', ' 77.5% ', ' 1.1% ']
[' 19 ', '  Germany  ', ' 83,644,258 ', ' −0.51% ', ' −430,817 ', ' 240 ', ' 348,560 ', ' 158,442 ', ' 1.46 ', ' 45.7 ', ' 77% ', ' 1% ']
[' 20 ', '  Tanzania  ', ' 72,563,780 ', ' 2.86% ', ' 2,017,915 ', ' 82 ', ' 885,800 ', ' −25,275 ', ' 4.41 ', ' 17.6 ', ' 40.8% ', ' 0.87% ']
[' 21 ', '  Thailand  ', ' 71,559,614 ', ' −0.08% ', ' −60,249 ', ' 140 ', ' 510,890 ', ' 29,200 ', ' 1.19 ', ' 41 ', ' 54.3% ', ' 0.86% ']
[' 22 ', '  United Kingdom  ', ' 69,931,528 ', ' 0.55% ', ' 380,196 ', ' 289 ', ' 241,930 ', ' 364,099 ', ' 1.53 ', ' 40.2 ', ' 84.7% ', ' 0.84% ']
[' 23 ', '  France  ', ' 66,746,401 ', ' 0.14% ', ' 95,597 ', ' 122 ', ' 547,557 ', ' 88,533 ', ' 1.64 ', ' 42.5 ', ' 83% ', ' 0.8% ']
[' 24 ', '  South Africa  ', ' 65,453,084 ', ' 1.09% ', ' 705,765 ', ' 54 ', ' 1,213,090 ', ' 131,684 ', ' 2.17 ', ' 28.9 ', ' 66.9% ', ' 0.79% ']
[' 25 ', '  Italy  ', ' 58,926,166 ', ' −0.37% ', ' −220,094 ', ' 200 ', ' 294,140 ', ' 58,272 ', ' 1.22 ', ' 48.6 ', ' 72.4% ', ' 0.71% ']
[' 26 ', '  Kenya  ', ' 58,636,412 ', ' 1.92% ', ' 1,103,919 ', ' 103 ', ' 569,140 ', ' −34,838 ', ' 3.07 ', ' 20.3 ', ' 32.6% ', ' 0.71% ']
[' 27 ', '  Myanmar  ', ' 55,184,819 ', ' 0.61% ', ' 334,171 ', ' 84 ', ' 653,290 ', ' −40,682 ', ' 2.06 ', ' 30.4 ', ' 34.6% ', ' 0.66% ']
[' 28 ', '  Colombia  ', ' 53,936,226 ', ' 0.96% ', ' 510,591 ', ' 49 ', ' 1,109,500 ', ' 115,815 ', ' 1.6 ', ' 33 ', ' 80.5% ', ' 0.65% ']
[' 29 ', '  Sudan  ', ' 53,282,719 ', ' 3.14% ', ' 1,620,572 ', ' 30 ', ' 1,765,048 ', ' 252,038 ', ' 4.13 ', ' 18.8 ', ' 35.4% ', ' 0.64% ']
[' 30 ', '  Uganda  ', ' 52,761,469 ', ' 2.68% ', ' 1,376,575 ', ' 264 ', ' 199,810 ', ' −121,799 ', ' 3.97 ', ' 17.1 ', ' 30.8% ', ' 0.64% ']
[' 31 ', '  South Korea  ', ' 51,600,388 ', ' −0.13% ', ' −66,641 ', ' 531 ', ' 97,230 ', ' 62,644 ', ' 0.76 ', ' 46.2 ', ' 82.8% ', ' 0.62% ']
[' 32 ', '  Algeria  ', ' 48,028,334 ', ' 1.25% ', ' 593,022 ', ' 20 ', ' 2,381,740 ', ' −28,841 ', ' 2.62 ', ' 28.8 ', ' 74.8% ', ' 0.58% ']
[' 33 ', '  Iraq  ', ' 48,007,437 ', ' 2.1% ', ' 986,663 ', ' 111 ', ' 434,320 ', ' −13,102 ', ' 3.13 ', ' 21.1 ', ' 73% ', ' 0.58% ']
[' 34 ', '  Spain  ', ' 47,850,793 ', ' −0.08% ', ' −39,165 ', ' 96 ', ' 498,800 ', ' 85,305 ', ' 1.24 ', ' 46.3 ', ' 79.6% ', ' 0.58% ']
[' 35 ', '  Argentina  ', ' 46,003,734 ', ' 0.33% ', ' 152,356 ', ' 17 ', ' 2,736,690 ', ' 2,316 ', ' 1.51 ', ' 33.3 ', ' 96.5% ', ' 0.55% ']
[' 36 ', '  Afghanistan  ', ' 45,047,069 ', ' 2.74% ', ' 1,202,958 ', ' 69 ', ' 652,860 ', ' −53,884 ', ' 4.56 ', ' 17.4 ', ' 26.9% ', ' 0.54% ']
[' 37 ', '  Yemen  ', ' 42,961,653 ', ' 2.84% ', ' 1,187,775 ', ' 81 ', ' 527,970 ', ' −22,178 ', ' 4.33 ', ' 18.5 ', ' 33.3% ', ' 0.52% ']
[' 38 ', '  Canada  ', ' 40,467,728 ', ' 0.85% ', ' 341,005 ', ' 4 ', ' 9,093,510 ', ' 291,403 ', ' 1.33 ', ' 40.8 ', ' 80.2% ', ' 0.49% ']
[' 39 ', '  Angola  ', ' 40,215,179 ', ' 3.01% ', ' 1,175,140 ', ' 32 ', ' 1,246,700 ', ' −4,270 ', ' 4.89 ', ' 16.7 ', ' 69.4% ', ' 0.48% ']
[' 40 ', '  Ukraine  ', ' 39,535,849 ', ' 1.43% ', ' 555,473 ', ' 68 ', ' 579,320 ', ' −6,229 ', ' 1 ', ' 41.8 ', ' 75.5% ', ' 0.48% ']
[' 41 ', '  Morocco  ', ' 38,762,441 ', ' 0.86% ', ' 331,671 ', ' 87 ', ' 446,300 ', ' −60,886 ', ' 2.16 ', ' 30.1 ', ' 67.9% ', ' 0.47% ']
[' 42 ', '  Poland  ', ' 37,843,188 ', ' −0.78% ', ' −297,722 ', ' 124 ', ' 306,230 ', ' −7,971 ', ' 1.31 ', ' 43 ', ' 59.7% ', ' 0.46% ']
[' 43 ', '  Uzbekistan  ', ' 37,724,223 ', ' 1.81% ', ' 670,795 ', ' 89 ', ' 425,400 ', ' −4,517 ', ' 3.4 ', ' 27 ', ' 47.9% ', ' 0.45% ']
[' 44 ', '  Mozambique  ', ' 36,639,851 ', ' 2.83% ', ' 1,008,198 ', ' 47 ', ' 786,380 ', ' −55,988 ', ' 4.54 ', ' 16.6 ', ' 42.1% ', ' 0.44% ']
[' 45 ', '  Malaysia  ', ' 36,385,115 ', ' 1.13% ', ' 407,277 ', ' 111 ', ' 328,550 ', ' 159,001 ', ' 1.52 ', ' 31.4 ', ' 77.8% ', ' 0.44% ']
[' 46 ', '  Ghana  ', ' 35,697,557 ', ' 1.81% ', ' 633,285 ', ' 157 ', ' 227,540 ', ' −24,195 ', ' 3.26 ', ' 21.6 ', ' 59.2% ', ' 0.43% ']
[' 47 ', '  Saudi Arabia  ', ' 35,165,787 ', ' 1.73% ', ' 599,459 ', ' 16 ', ' 2,149,690 ', ' 108,660 ', ' 2.27 ', ' 29.7 ', ' 91.9% ', ' 0.42% ']
[' 48 ', '  Peru  ', ' 34,922,148 ', ' 1% ', ' 345,483 ', ' 27 ', ' 1,280,000 ', ' 6,707 ', ' 1.93 ', ' 30.6 ', ' 80.9% ', ' 0.42% ']
[' 49 ', '  Madagascar  ', ' 33,522,052 ', ' 2.39% ', ' 781,374 ', ' 58 ', ' 581,795 ', ' −2,665 ', ' 3.78 ', ' 19.4 ', ' 41% ', ' 0.4% ']
[' 50 ', "  Côte d'Ivoire  ", ' 33,494,346 ', ' 2.39% ', ' 782,799 ', ' 105 ', ' 318,000 ', ' 6,535 ', ' 4.1 ', ' 18.5 ', ' 49.5% ', ' 0.4% ']
[' 51 ', '  Cameroon  ', ' 30,640,817 ', ' 2.55% ', ' 761,480 ', ' 65 ', ' 472,710 ', ' −18,922 ', ' 4.12 ', ' 18.2 ', ' 59.8% ', ' 0.37% ']
[' 52 ', '  Nepal  ', ' 29,629,410 ', ' 0.04% ', ' 11,292 ', ' 207 ', ' 143,350 ', ' −292,014 ', ' 1.92 ', ' 25.7 ', ' 25.3% ', ' 0.36% ']
[' 53 ', '  Niger  ', ' 28,814,878 ', ' 3.21% ', ' 897,047 ', ' 23 ', ' 1,266,700 ', ' −10,620 ', ' 5.64 ', ' 15.7 ', ' 18.5% ', ' 0.35% ']
[' 54 ', '  Venezuela  ', ' 28,633,711 ', ' 0.41% ', ' 116,815 ', ' 32 ', ' 882,050 ', ' −92,869 ', ' 2.04 ', ' 29.5 ', ' – ', ' 0.34% ']
[' 55 ', '  Australia  ', ' 27,227,096 ', ' 0.94% ', ' 253,070 ', ' 4 ', ' 7,682,300 ', ' 131,706 ', ' 1.64 ', ' 38.5 ', ' 86.7% ', ' 0.33% ']
[' 56 ', '  North Korea  ', ' 26,633,691 ', ' 0.24% ', ' 62,655 ', ' 221 ', ' 120,410 ', ' −2,809 ', ' 1.75 ', ' 36.8 ', ' 63.7% ', ' 0.32% ']
[' 57 ', '  Syria  ', ' 26,472,497 ', ' 3.33% ', ' 852,070 ', ' 144 ', ' 183,630 ', ' 305,822 ', ' 2.62 ', ' 23.8 ', ' 54.2% ', ' 0.32% ']
[' 58 ', '  Mali  ', ' 25,932,275 ', ' 2.91% ', ' 733,454 ', ' 21 ', ' 1,220,190 ', ' −52,609 ', ' 5.33 ', ' 15.9 ', ' 45.1% ', ' 0.31% ']
[' 59 ', '  Burkina Faso  ', ' 24,601,700 ', ' 2.19% ', ' 527,120 ', ' 90 ', ' 273,600 ', ' −28,309 ', ' 3.92 ', ' 18 ', ' 34.5% ', ' 0.3% ']
[' 60 ', '  Sri Lanka  ', ' 23,348,315 ', ' 0.51% ', ' 118,845 ', ' 372 ', ' 62,710 ', ' −30,760 ', ' 1.93 ', ' 33.6 ', ' 18.2% ', ' 0.28% ']
[' 61 ', '  Taiwan  ', ' 23,011,292 ', ' −0.44% ', ' −101,501 ', ' 650 ', ' 35,410 ', ' −15,041 ', ' 0.86 ', ' 45.4 ', ' 84.9% ', ' 0.28% ']
[' 62 ', '  Malawi  ', ' 22,785,535 ', ' 2.56% ', ' 569,415 ', ' 242 ', ' 94,280 ', ' 1,348 ', ' 3.45 ', ' 18.4 ', ' 20.2% ', ' 0.27% ']
[' 63 ', '  Zambia  ', ' 22,521,915 ', ' 2.77% ', ' 608,041 ', ' 30 ', ' 743,390 ', ' 6,939 ', ' 3.91 ', ' 18.2 ', ' 47.4% ', ' 0.27% ']
[' 64 ', '  Chad  ', ' 21,560,380 ', ' 2.65% ', ' 556,675 ', ' 17 ', ' 1,259,200 ', ' −112,304 ', ' 5.83 ', ' 15.7 ', ' 22.7% ', ' 0.26% ']
[' 65 ', '  Kazakhstan  ', ' 21,083,626 ', ' 1.15% ', ' 239,872 ', ' 8 ', ' 2,699,700 ', ' −12,814 ', ' 2.92 ', ' 29.7 ', ' 55.2% ', ' 0.25% ']
[' 66 ', '  Somalia  ', ' 20,305,907 ', ' 3.31% ', ' 651,168 ', ' 32 ', ' 627,340 ', ' 15,364 ', ' 5.8 ', ' 15.6 ', ' 47.1% ', ' 0.24% ']
[' 67 ', '  Chile  ', ' 19,945,850 ', ' 0.43% ', ' 85,929 ', ' 27 ', ' 743,532 ', ' 48,106 ', ' 1.12 ', ' 37.4 ', ' 85.1% ', ' 0.24% ']
[' 68 ', '  Senegal  ', ' 19,366,548 ', ' 2.3% ', ' 434,582 ', ' 101 ', ' 192,530 ', ' −13,429 ', ' 3.66 ', ' 19.8 ', ' 53% ', ' 0.23% ']
[' 69 ', '  Guatemala  ', ' 18,967,978 ', ' 1.5% ', ' 280,097 ', ' 177 ', ' 107,160 ', ' −7,432 ', ' 2.23 ', ' 23.8 ', ' 57.1% ', ' 0.23% ']
[' 70 ', '  Romania  ', ' 18,800,605 ', ' −0.57% ', ' −108,045 ', ' 82 ', ' 230,170 ', ' −28,982 ', ' 1.71 ', ' 43.5 ', ' 55.5% ', ' 0.23% ']
[' 71 ', '  Netherlands  ', ' 18,448,775 ', ' 0.56% ', ' 101,956 ', ' 547 ', ' 33,720 ', ' 89,379 ', ' 1.44 ', ' 41.5 ', ' 88.9% ', ' 0.22% ']
[' 72 ', '  Ecuador  ', ' 18,444,506 ', ' 0.85% ', ' 154,610 ', ' 74 ', ' 248,360 ', ' −13,851 ', ' 1.78 ', ' 29.7 ', ' 66.4% ', ' 0.22% ']
[' 73 ', '  Cambodia  ', ' 18,051,219 ', ' 1.14% ', ' 203,237 ', ' 102 ', ' 176,520 ', ' −34,323 ', ' 2.49 ', ' 26.4 ', ' 26.9% ', ' 0.22% ']
[' 74 ', '  Zimbabwe  ', ' 17,273,580 ', ' 1.9% ', ' 322,785 ', ' 45 ', ' 386,850 ', ' −54,620 ', ' 3.57 ', ' 18.3 ', ' 38.2% ', ' 0.21% ']
[' 75 ', '  Guinea  ', ' 15,441,993 ', ' 2.27% ', ' 342,266 ', ' 63 ', ' 245,720 ', ' −19,725 ', ' 3.96 ', ' 18.5 ', ' 40.9% ', ' 0.19% ']
[' 76 ', '  Benin  ', ' 15,170,419 ', ' 2.4% ', ' 355,959 ', ' 135 ', ' 112,760 ', ' −6,318 ', ' 4.34 ', ' 18.2 ', ' 48.4% ', ' 0.18% ']
[' 77 ', '  Rwanda  ', ' 14,889,693 ', ' 2.2% ', ' 320,352 ', ' 604 ', ' 24,670 ', ' −7,003 ', ' 3.54 ', ' 20.2 ', ' 18.5% ', ' 0.18% ']
[' 78 ', '  Burundi  ', ' 14,729,157 ', ' 2.36% ', ' 339,154 ', ' 574 ', ' 25,680 ', ' −35,108 ', ' 4.57 ', ' 16.6 ', ' 15.4% ', ' 0.18% ']
[' 79 ', '  Bolivia  ', ' 12,749,291 ', ' 1.33% ', ' 167,448 ', ' 12 ', ' 1,083,300 ', ' −3,157 ', ' 2.47 ', ' 25.5 ', ' 71% ', ' 0.15% ']
[' 80 ', '  South Sudan  ', ' 12,436,037 ', ' 2.03% ', ' 247,249 ', ' 20 ', ' 610,952 ', ' 7,974 ', ' 3.63 ', ' 19 ', ' 28.3% ', ' 0.15% ']
[' 81 ', '  Tunisia  ', ' 12,415,138 ', ' 0.54% ', ' 66,565 ', ' 80 ', ' 155,360 ', ' −14,794 ', ' 1.79 ', ' 33.4 ', ' 72.2% ', ' 0.15% ']
[' 82 ', '  Haiti  ', ' 12,037,506 ', ' 1.1% ', ' 131,411 ', ' 437 ', ' 27,560 ', ' −31,968 ', ' 2.55 ', ' 24.3 ', ' 62.4% ', ' 0.15% ']
[' 83 ', '  Belgium  ', ' 11,774,642 ', ' 0.14% ', ' 16,039 ', ' 389 ', ' 30,280 ', ' 29,607 ', ' 1.4 ', ' 42.1 ', ' 99% ', ' 0.14% ']
[' 84 ', '  Dominican Republic  ', ' 11,609,500 ', ' 0.77% ', ' 89,013 ', ' 240 ', ' 48,320 ', ' −35,038 ', ' 2.17 ', ' 28.7 ', ' 86.9% ', ' 0.14% ']
[' 85 ', '  Jordan  ', ' 11,589,532 ', ' 0.6% ', ' 68,848 ', ' 131 ', ' 88,780 ', ' 60,699 ', ' 2.54 ', ' 24.9 ', ' 85.4% ', ' 0.14% ']
[' 86 ', '  United Arab Emirates  ', ' 11,574,682 ', ' 2.02% ', ' 228,682 ', ' 138 ', ' 83,600 ', ' 87,401 ', ' 1.21 ', ' 31.6 ', ' 80.7% ', ' 0.14% ']
[' 87 ', '  Honduras  ', ' 11,184,760 ', ' 1.63% ', ' 178,910 ', ' 100 ', ' 111,890 ', ' −4,603 ', ' 2.42 ', ' 24.6 ', ' 58.8% ', ' 0.13% ']
[' 88 ', '  Tajikistan  ', ' 10,978,599 ', ' 1.78% ', ' 191,865 ', ' 78 ', ' 139,960 ', ' −20,198 ', ' 2.96 ', ' 22.4 ', ' 28% ', ' 0.13% ']
[' 89 ', '  Papua New Guinea  ', ' 10,947,848 ', ' 1.72% ', ' 185,031 ', ' 24 ', ' 452,860 ', ' −534 ', ' 2.99 ', ' 23 ', ' 12.7% ', ' 0.13% ']
[' 90 ', '  Cuba  ', ' 10,892,659 ', ' −0.41% ', ' −44,544 ', ' 102 ', ' 106,440 ', ' −22,086 ', ' 1.46 ', ' 42.5 ', ' 82.4% ', ' 0.13% ']
[' 91 ', '  Sweden  ', ' 10,701,047 ', ' 0.42% ', ' 44,414 ', ' 26 ', ' 410,340 ', ' 42,755 ', ' 1.45 ', ' 40.4 ', ' 87.7% ', ' 0.13% ']
[' 92 ', '  Czech Republic (Czechia)  ', ' 10,527,781 ', ' −0.77% ', ' −81,458 ', ' 136 ', ' 77,240 ', ' 13,400 ', ' 1.47 ', ' 44.3 ', ' 75.7% ', ' 0.13% ']
[' 93 ', '  Azerbaijan  ', ' 10,454,855 ', ' 0.55% ', ' 57,142 ', ' 126 ', ' 82,658 ', ' 7,708 ', ' 1.66 ', ' 34.1 ', ' 59.1% ', ' 0.13% ']
[' 94 ', '  Portugal  ', ' 10,395,362 ', ' −0.16% ', ' −16,472 ', ' 113 ', ' 91,590 ', ' 16,968 ', ' 1.52 ', ' 47.2 ', ' 66.9% ', ' 0.13% ']
[' 95 ', '  Togo  ', ' 9,930,918 ', ' 2.15% ', ' 209,310 ', ' 183 ', ' 54,390 ', ' −12,642 ', ' 4.01 ', ' 19.2 ', ' 44.8% ', ' 0.12% ']
[' 96 ', '  Greece  ', ' 9,897,115 ', ' −0.42% ', ' −41,729 ', ' 77 ', ' 128,900 ', ' 14,649 ', ' 1.34 ', ' 47.1 ', ' 90% ', ' 0.12% ']
[' 97 ', '  Israel  ', ' 9,647,689 ', ' 1.37% ', ' 130,508 ', ' 446 ', ' 21,640 ', ' 13,023 ', ' 2.73 ', ' 29.3 ', ' 91.5% ', ' 0.12% ']
[' 98 ', '  Hungary  ', ' 9,585,818 ', ' −0.48% ', ' −46,469 ', ' 106 ', ' 90,530 ', ' 12,936 ', ' 1.5 ', ' 44.2 ', ' 72.4% ', ' 0.12% ']
[' 99 ', '  Austria  ', ' 9,107,266 ', ' −0.07% ', ' −6,308 ', ' 111 ', ' 82,409 ', ' 13,212 ', ' 1.34 ', ' 43.9 ', ' 59% ', ' 0.11% ']
[' 100 ', '  Switzerland  ', ' 9,007,798 ', ' 0.45% ', ' 40,391 ', ' 228 ', ' 39,516 ', ' 34,096 ', ' 1.45 ', ' 43.2 ', ' 74.6% ', ' 0.11% ']
[' 101 ', '  Sierra Leone  ', ' 8,996,745 ', ' 2.01% ', ' 176,951 ', ' 125 ', ' 72,180 ', ' −12,277 ', ' 3.53 ', ' 19.9 ', ' 46% ', ' 0.11% ']
[' 102 ', '  Belarus  ', ' 8,937,018 ', ' −0.67% ', ' −60,585 ', ' 44 ', ' 202,910 ', ' −3,608 ', ' 1.23 ', ' 41.8 ', ' 85.1% ', ' 0.11% ']
[' 103 ', '  Laos  ', ' 7,974,017 ', ' 1.28% ', ' 100,971 ', ' 35 ', ' 230,800 ', ' −11,125 ', ' 2.33 ', ' 25.3 ', ' 38.9% ', ' 0.1% ']
[' 104 ', '  Turkmenistan  ', ' 7,736,632 ', ' 1.55% ', ' 117,785 ', ' 16 ', ' 469,930 ', ' 11,792 ', ' 2.6 ', ' 27.3 ', ' 46.7% ', ' 0.09% ']
[' 105 ', '  Libya  ', ' 7,539,851 ', ' 1.09% ', ' 81,296 ', ' 4 ', ' 1,759,540 ', ' 2,610 ', ' 2.21 ', ' 28 ', ' 77.7% ', ' 0.09% ']
[' 106 ', '  Kyrgyzstan  ', ' 7,400,465 ', ' 1.45% ', ' 105,431 ', ' 39 ', ' 191,800 ', ' 39 ', ' 2.72 ', ' 25.5 ', ' 35.5% ', ' 0.09% ']
[' 107 ', '  Hong Kong  ', ' 7,378,602 ', ' −0.24% ', ' −17,474 ', ' 7,027 ', ' 1,050 ', ' −12,576 ', ' 0.75 ', ' 47.9 ', ' – ', ' 0.09% ']
[' 108 ', '  Nicaragua  ', ' 7,097,329 ', ' 1.28% ', ' 89,827 ', ' 59 ', ' 120,340 ', ' −8,485 ', ' 2.16 ', ' 26.3 ', ' 58.2% ', ' 0.09% ']
[' 109 ', '  Paraguay  ', ' 7,095,279 ', ' 1.17% ', ' 82,201 ', ' 18 ', ' 397,300 ', ' −12,243 ', ' 2.37 ', ' 27.3 ', ' 68.3% ', ' 0.09% ']
[' 110 ', '  Bulgaria  ', ' 6,667,659 ', ' −0.7% ', ' −46,901 ', ' 61 ', ' 108,560 ', ' −5,722 ', ' 1.74 ', ' 45 ', ' 77.4% ', ' 0.08% ']
[' 111 ', '  Serbia  ', ' 6,641,964 ', ' −0.7% ', ' −47,075 ', ' 76 ', ' 87,460 ', ' −5,883 ', ' 1.5 ', ' 44.7 ', ' 74.2% ', ' 0.08% ']
[' 112 ', '  Congo  ', ' 6,637,785 ', ' 2.36% ', ' 153,348 ', ' 19 ', ' 341,500 ', ' −3,298 ', ' 3.99 ', ' 18.7 ', ' 70.3% ', ' 0.08% ']
[' 113 ', '  El Salvador  ', ' 6,391,253 ', ' 0.4% ', ' 25,750 ', ' 308 ', ' 20,720 ', ' −23,530 ', ' 1.74 ', ' 28.4 ', ' 80.5% ', ' 0.08% ']
[' 114 ', '  Denmark  ', ' 6,023,520 ', ' 0.35% ', ' 21,013 ', ' 142 ', ' 42,430 ', ' 18,360 ', ' 1.52 ', ' 41.3 ', ' 87.6% ', ' 0.07% ']
[' 115 ', '  Singapore  ', ' 5,905,748 ', ' 0.6% ', ' 34,998 ', ' 8,437 ', ' 700 ', ' 13,379 ', ' 0.97 ', ' 36.8 ', ' – ', ' 0.07% ']
[' 116 ', '  Lebanon  ', ' 5,897,467 ', ' 0.82% ', ' 48,046 ', ' 576 ', ' 10,230 ', ' −6,685 ', ' 2.19 ', ' 29 ', ' 84.4% ', ' 0.07% ']
[' 117 ', '  Liberia  ', ' 5,853,949 ', ' 2.14% ', ' 122,743 ', ' 61 ', ' 96,320 ', ' −1,051 ', ' 3.71 ', ' 19 ', ' 55.7% ', ' 0.07% ']
[' 118 ', '  Central African Republic  ', ' 5,698,984 ', ' 3.37% ', ' 185,702 ', ' 9 ', ' 622,980 ', ' −15,608 ', ' 5.69 ', ' 14.6 ', ' 44.5% ', ' 0.07% ']
[' 119 ', '  State of Palestine  ', ' 5,692,790 ', ' 1.85% ', ' 103,167 ', ' 946 ', ' 6,020 ', ' −20,055 ', ' 3.13 ', ' 20.3 ', ' 85% ', ' 0.07% ']
[' 120 ', '  Oman  ', ' 5,671,458 ', ' 3.22% ', ' 176,767 ', ' 18 ', ' 309,500 ', ' 79,740 ', ' 2.44 ', ' 29.8 ', ' 89.6% ', ' 0.07% ']
[' 121 ', '  Norway  ', ' 5,652,989 ', ' 0.53% ', ' 29,918 ', ' 15 ', ' 365,268 ', ' 12,047 ', ' 1.42 ', ' 40.1 ', ' 86.5% ', ' 0.07% ']
[' 122 ', '  Finland  ', ' 5,621,739 ', ' −0.03% ', ' −1,590 ', ' 18 ', ' 303,890 ', ' 12,666 ', ' 1.3 ', ' 43.4 ', ' 87.1% ', ' 0.07% ']
[' 123 ', '  Mauritania  ', ' 5,461,319 ', ' 2.75% ', ' 146,254 ', ' 5 ', ' 1,030,700 ', ' −5,842 ', ' 4.49 ', ' 17.5 ', ' 60.9% ', ' 0.07% ']
[' 124 ', '  Slovakia  ', ' 5,451,342 ', ' −0.43% ', ' −23,539 ', ' 113 ', ' 48,088 ', ' 134 ', ' 1.57 ', ' 42.8 ', ' 54.3% ', ' 0.07% ']
[' 125 ', '  Ireland  ', ' 5,356,950 ', ' 0.92% ', ' 48,911 ', ' 78 ', ' 68,890 ', ' 32,022 ', ' 1.6 ', ' 39.2 ', ' 62.2% ', ' 0.06% ']
[' 126 ', '  New Zealand  ', ' 5,287,479 ', ' 0.68% ', ' 35,580 ', ' 20 ', ' 263,310 ', ' 16,435 ', ' 1.64 ', ' 38 ', ' 83.7% ', ' 0.06% ']
[' 127 ', '  Costa Rica  ', ' 5,174,789 ', ' 0.42% ', ' 21,839 ', ' 101 ', ' 51,060 ', ' 966 ', ' 1.31 ', ' 35.7 ', ' 85.9% ', ' 0.06% ']
[' 128 ', '  Kuwait  ', ' 5,102,773 ', ' 1.53% ', ' 76,695 ', ' 286 ', ' 17,820 ', ' 30,696 ', ' 1.49 ', ' 34.8 ', ' 91.3% ', ' 0.06% ']
[' 129 ', '  Panama  ', ' 4,625,718 ', ' 1.19% ', ' 54,529 ', ' 62 ', ' 74,340 ', ' 5,665 ', ' 2.07 ', ' 30.6 ', ' 71.1% ', ' 0.06% ']
[' 130 ', '  Croatia  ', ' 3,822,345 ', ' −0.67% ', ' −25,815 ', ' 68 ', ' 55,960 ', ' −2,491 ', ' 1.47 ', ' 45.5 ', ' 62.2% ', ' 0.05% ']
[' 131 ', '  Georgia  ', ' 3,804,642 ', ' −0.05% ', ' −2,029 ', ' 55 ', ' 69,490 ', ' 1,215 ', ' 1.78 ', ' 37.6 ', ' 62.2% ', ' 0.05% ']
[' 132 ', '  Eritrea  ', ' 3,682,669 ', ' 2.1% ', ' 75,666 ', ' 36 ', ' 101,000 ', ' −7,520 ', ' 3.55 ', ' 19.5 ', ' 75.9% ', ' 0.04% ']
[' 133 ', '  Mongolia  ', ' 3,556,798 ', ' 1.13% ', ' 39,698 ', ' 2 ', ' 1,553,560 ', ' 12 ', ' 2.54 ', ' 27 ', ' 67.3% ', ' 0.04% ']
[' 134 ', '  Uruguay  ', ' 3,382,537 ', ' −0.06% ', ' −2,151 ', ' 19 ', ' 175,020 ', ' −1,413 ', ' 1.38 ', ' 36.7 ', ' – ', ' 0.04% ']
[' 135 ', '  Puerto Rico  ', ' 3,222,688 ', ' −0.39% ', ' −12,601 ', ' 363 ', ' 8,870 ', ' 1,056 ', ' 0.94 ', ' 46.2 ', ' – ', ' 0.04% ']
[' 136 ', '  Qatar  ', ' 3,173,559 ', ' 1.85% ', ' 57,670 ', ' 273 ', ' 11,610 ', ' 24,791 ', ' 1.69 ', ' 33.4 ', ' 96.2% ', ' 0.04% ']
[' 137 ', '  Namibia  ', ' 3,153,246 ', ' 1.95% ', ' 60,430 ', ' 4 ', ' 823,290 ', ' 47 ', ' 3.13 ', ' 21.5 ', ' 55.2% ', ' 0.04% ']
[' 138 ', '  Bosnia and Herzegovina  ', ' 3,114,242 ', ' −0.82% ', ' −25,853 ', ' 61 ', ' 51,000 ', ' −7,581 ', ' 1.5 ', ' 46.1 ', ' 57.1% ', ' 0.04% ']
[' 139 ', '  Moldova  ', ' 2,961,253 ', ' −1.16% ', ' −34,853 ', ' 90 ', ' 32,850 ', ' −16,732 ', ' 1.72 ', ' 39.1 ', ' 58.5% ', ' 0.04% ']
[' 140 ', '  Armenia  ', ' 2,930,915 ', ' −0.73% ', ' −21,450 ', ' 103 ', ' 28,470 ', ' −27,000 ', ' 1.71 ', ' 37.2 ', ' 64.4% ', ' 0.04% ']
[' 141 ', '  Gambia  ', ' 2,884,079 ', ' 2.2% ', ' 61,986 ', ' 285 ', ' 10,120 ', ' −2,894 ', ' 3.7 ', ' 18.8 ', ' 62.2% ', ' 0.03% ']
[' 142 ', '  Jamaica  ', ' 2,833,403 ', ' −0.13% ', ' −3,674 ', ' 262 ', ' 10,830 ', ' −11,683 ', ' 1.33 ', ' 33.3 ', ' 60.7% ', ' 0.03% ']

In [28]:
for row in column_data[1:]:
    row_data = row.find_all('td')
    individual_row_data = [data.text.strip().replace("−", "-") for data in row_data]

    length = len(df)
    df.loc[length] = individual_row_data

In [29]:
df

,#,Country (or dependency),Population 2026,Yearly Change,Net Change,Density (P/Km²),Land Area (Km²),Migrants (net),Fert. Rate,Median Age,Urban Pop %,World Share
0,1,India,"1,476,625,576",0.87%,"12,760,051",497,"2,973,190","-440,456",1.93,29.2,37.6%,17.8%
1,2,China,"1,412,914,089",-0.22%,"-3,182,005",150,"9,388,211","-232,107",1.03,40.6,68.7%,17%
2,3,United States,"349,035,494",0.51%,"1,759,687",38,"9,147,420","1,177,848",1.63,38.7,83.1%,4.2%
3,4,Indonesia,"287,886,782",0.76%,"2,165,546",159,"1,811,570","-39,472",2.08,30.7,60.3%,3.5%
4,5,Pakistan,"259,299,791",1.6%,"4,080,237",336,"770,880","-1,144,738",3.44,20.8,34.7%,3.1%
...,...,...,...,...,...,...,...,...,...,...,...,...
229,230,Montserrat,"4,328",-0.71%,-31,43,100,-10,1.45,41.8,11.7%,0.000052%
230,231,Falkland Islands,"3,465",-0.12%,-4,0,"12,170",-16,1.69,43.4,68.4%,0.000042%
231,232,Tokelau,"2,691",3.18%,83,269,10,43,2.54,27.6,–,0.000032%
232,233,Niue,"1,822",0.05%,1,7,260,2,2.44,35.1,45.2%,0.000022%
233,234,Holy See,506,1%,5,"1,265",0,13,1,56.2,–,0.0000061%

In [ ]:
df.to_csv(r'C:path\to\World_Population.csv', index = False, encoding="utf-8-sig")